### ISSUE TITLE
error saving credentials for algolia/typesense

### ISSUE THREAD

**Issue by dankoz51** [develodesign/magento2-module-typesense#12]
on magento 2.4.6 on php 8.1 I am getting this error when trying to save the algolia/typsense credentials

ArgumentCountError: Too few arguments to function Algolia\AlgoliaSearch\Model\Observer\SaveSettings::execute(), 0 passed in /var/www/html/vendor/magento/framework/Interception/Interceptor.php on line 58 and exactly 1 expected in /var/www/html/vendor/algolia/algoliasearch-magento-2/Model/Observer/SaveSettings.php:63
Stack trace:
#0 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Algolia\AlgoliaSearch\Model\Observer\SaveSettings->execute()
#1 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Algolia\AlgoliaSearch\Model\Observer\SaveSettings\Interceptor->___callParent('execute', Array)
#2 /var/www/html/vendor/develodesign/magento2-module-typesense/Plugin/Algolia/AlgoliaSearch/Model/SaveSettings.php(37): Algolia\AlgoliaSearch\Model\Observer\SaveSettings\Interceptor->Magento\Framework\Interception\{closure}()
#3 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Develo\Typesense\Plugin\Algolia\AlgoliaSearch\Model\SaveSettings->aroundExecute(Object(Algolia\AlgoliaSearch\Model\Observer\SaveSettings\Interceptor), Object(Closure), Object(Magento\Framework\Event\Observer))
#4 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Algolia\AlgoliaSearch\Model\Observer\SaveSettings\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\Event\Observer))
#5 /var/www/html/generated/code/Algolia/AlgoliaSearch/Model/Observer/SaveSettings/Interceptor.php(23): Algolia\AlgoliaSearch\Model\Observer\SaveSettings\Interceptor->___callPlugins('execute', Array, NULL)
#6 /var/www/html/vendor/magento/framework/Event/Invoker/InvokerDefault.php(88): Algolia\AlgoliaSearch\Model\Observer\SaveSettings\Interceptor->execute(Object(Magento\Framework\Event\Observer))
#7 /var/www/html/vendor/magento/framework/Event/Invoker/InvokerDefault.php(74): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Algolia\AlgoliaSearch\Model\Observer\SaveSettings\Interceptor), Object(Magento\Framework\Event\Observer))
#8 /var/www/html/vendor/magento/framework/Event/Manager.php(65): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))
#9 /var/www/html/generated/code/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch('admin_system_co...', Array)
#10 /var/www/html/vendor/magento/module-config/Model/Config.php(225): Magento\Framework\Event\Manager\Proxy->dispatch('admin_system_co...', Array)
#11 /var/www/html/vendor/magento/module-config/Controller/Adminhtml/System/Config/Save.php(241): Magento\Config\Model\Config->save()
#12 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Config\Controller\Adminhtml\System\Config\Save->execute()
#13 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Algolia\AlgoliaSearch\Controller\Adminhtml\System\Config\Save\Interceptor->___callParent('execute', Array)
#14 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Algolia\AlgoliaSearch\Controller\Adminhtml\System\Config\Save\Interceptor->Magento\Framework\Interception\{closure}()
#15 /var/www/html/generated/code/Algolia/AlgoliaSearch/Controller/Adminhtml/System/Config/Save/Interceptor.php(23): Algolia\AlgoliaSearch\Controller\Adminhtml\System\Config\Save\Interceptor->___callPlugins('execute', Array, Array)
#16 /var/www/html/vendor/magento/framework/App/Action/Action.php(111): Algolia\AlgoliaSearch\Controller\Adminhtml\System\Config\Save\Interceptor->execute()
#17 /var/www/html/vendor/magento/module-backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#18 /var/www/html/vendor/magento/module-config/Controller/Adminhtml/System/AbstractConfig.php(69): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#19 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Config\Controller\Adminhtml\System\AbstractConfig->dispatch(Object(Magento\Framework\App\Request\Http))
#20 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Algolia\AlgoliaSearch\Controller\Adminhtml\System\Config\Save\Interceptor->___callParent('dispatch', Array)
#21 /var/www/html/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(145): Algolia\AlgoliaSearch\Controller\Adminhtml\System\Config\Save\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#22 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Algolia\AlgoliaSearch\Controller\Adminhtml\System\Config\Save\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#23 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Algolia\AlgoliaSearch\Controller\Adminhtml\System\Config\Save\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#24 /var/www/html/generated/code/Algolia/AlgoliaSearch/Controller/Adminhtml/System/Config/Save/Interceptor.php(32): Algolia\AlgoliaSearch\Controller\Adminhtml\System\Config\Save\Interceptor->___callPlugins('dispatch', Array, Array)
#25 /var/www/html/vendor/magento/framework/App/FrontController.php(245): Algolia\AlgoliaSearch\Controller\Adminhtml\System\Config\Save\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#26 /var/www/html/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse(Object(Algolia\AlgoliaSearch\Controller\Adminhtml\System\Config\Save\Interceptor), Object(Magento\Framework\App\Request\Http))
#27 /var/www/html/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest(Object(Magento\Framework\App\Request\Http), Object(Algolia\AlgoliaSearch\Controller\Adminhtml\System\Config\Save\Interceptor))
#28 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#29 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#30 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#31 /var/www/html/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#32 /var/www/html/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#33 /var/www/html/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#34 /var/www/html/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#35 /var/www/html/pub/index.php(30): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#36 {main}

**Comment by brideo** [comment]
Thank you for the report @dankoz51  - it should work on the latest version:

```
composer require develodesign/magento2-module-typesense:^1.0.1
```

**Comment by dankoz51** [comment]
That seemed to do the trick in the ui.  After configuring this with typesense cloud sevices i get this when trying to reindex

Algolia Search Products index process error during indexation process:
Too few arguments to function Algolia\AlgoliaSearch\Model\IndicesConfigurator::saveConfigurationToAlgolia(), 0 passed in /var/www/html/vendor/magento/framework/Interception/Interceptor.php on line 58 and at least 1 expected
Algolia Search Categories index process error during indexation process:
Too few arguments to function Algolia\AlgoliaSearch\Model\IndicesConfigurator::saveConfigurationToAlgolia(), 0 passed in /var/www/html/vendor/magento/framework/Interception/Interceptor.php on line 58 and at least 1 expected
Algolia Search Pages index process error during indexation process:
Too few arguments to function Algolia\AlgoliaSearch\Helper\AlgoliaHelper::addObjects(), 0 passed in /var/www/html/vendor/magento/framework/Interception/Interceptor.php on line 58 and exactly 2 expected
Algolia Search Suggestions index process error during indexation process:
Too few arguments to function Algolia\AlgoliaSearch\Helper\AlgoliaHelper::copyQueryRules(), 0 passed in /var/www/html/vendor/magento/framework/Interception/Interceptor.php on line 58 and exactly 2 expected
Algolia Additional Sections index has been rebuilt successfully in 00:00:00
Algolia Search Queue Runner index has been rebuilt successfully in 00:00:00
Algolia Search - Delete inactive products index process error during indexation process:
Too few arguments to function Algolia\AlgoliaSearch\Helper\Data::deleteInactiveProducts(), 0 passed in /var/www/html/vendor/magento/framework/Interception/Interceptor.php on line 58 and exactly 1 expected

I can see product have not been pushed to the index but if i save individually it appears to possibly work.
