### ISSUE TITLE
Autocomplete performing algiolia search requests

### ISSUE THREAD

**Issue by organicinternet** [develodesign/magento2-module-typesense#9]
I'm a huge fan of Typesense so great to see you've put the effort into making use of Typesense in Magento.

I've installed the composer package on a Luma-based M2.4.4 site. Indexing is working, and instant search works (having disabled the price facet for now) however the autocomplete doesn't seem to be being overloaded to use Typesense - instead it's still performing algolia-style search requests.

I'm assuming it's because at no point in my set up is autocompleteConfig.js included, but I can't figure out what would cause it to be included as algolia-form is only mentioned in the hyva layout.

Should this be included for Luma too? Any idea what I'm missing?

**Comment by collymore** [comment]
Hi Simon, 
We're pushing an update for this today, so that will fix the price facet issue and a few others you've mentioned. It should work with Luma also yes. 

Thanks

**Comment by brideo** [comment]
Hi Simon,

Thank you for submitting the report. I wanted to let you know that we have scheduled a fix for the issue, which will be available on the following branch: https://github.com/develodesign/magento2-module-typesense/tree/feature/searchable-attributes-and-autocomplete

We will merge to `main` once we've tested.

As a part of the fix, we have made changes to how searchable attributes work. Therefore, it is recommended that you rebuild your collection schema and review your searchable attributes. I had to change attributes "path", "qty_sold", and "color" so they weren't searchable in the Algolia config.

Settings > Algolia > Products > Attributes

![image](https://user-images.githubusercontent.com/4906361/235909170-ac9d018c-b812-4af4-99b8-46c65d5f9aa8.png)

For further information, please refer to the updated README updates as I outline the issue there.

Thanks

**Comment by collymore** [comment]
Hi @organicinternet if you please pull the latest version these issues should be fixed now

**Comment by sajidunnar** [comment]
Hello ,

Thanks for the module , I am exploring this but I think I am stuck with some configuration  when I try to search something it try to fetch data from https://xyz-dsn.algolia.net/1/indexes/*/queries?x-algolia-agent=Algolia%20for%20JavaScript%20(4.14.3)%3B%20Browser%3B%20Magento2%20integration%20(3.13.1)%3B%20autocomplete-core%20(1.6.3)%3B%20autocomplete-js%20(1.6.3)
